### ISSUE TITLE
Request to rename the repo

### ISSUE THREAD

**Issue by adithyaselv** [algebraic-graphs/scala#2]
Can you rename repo to something like `Alga-Scala` may be for better clarity ? Its slightly confusing as its looked like fork of https://github.com/scala/scala at first glance

**Comment by snowleopard** [comment]
@adithyaselv I thought about this, but decided to keep the names short. 

I'm not a fan of having duplication like `github.com/algebraic-graphs/Alga-Scala` in full repo names.

Short names `agda` or `scala` may indeed be slightly confusing at first glance, but hopefully the confusion quickly goes away.

**Comment by adithyaselv** [comment]
👍
